version: "3.4"
services:
  webserver:
    build:
      context: ./personal_expense_ttracker
    ports:
      - "80:5000"
    links:
      - mysqldb
    restart: 'always'

    networks:
          network:
            ipv4_address: 10.5.0.4


  mysqldb:
    image: mysql:latest
    restart: 'always'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes: 
      - ./init:/docker-entrypoint-initdb.d

    environment:
      MYSQL_DATABASE: mymoney
      MYSQL_USER: vaisakhkm
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root_pass

    networks:
          network:
            ipv4_address: 10.5.0.5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'Phpmyadmin'
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
    ports:
      - '800:80'

    networks:
          network:
            ipv4_address: 10.5.0.6


networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
